services:
  - type: web
    name: skillbridge-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: FOLDER_NAME
        value: skillbridge
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: RAZORPAY_KEY
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
